# Github codespaces does not appear to use this file, but it may be useful for running devcontainers
# locally.

services:
  flaskdebugrun:
    image: ghcr.io/tomgobravo/tourist-builder:latest
    working_dir: /workspace/tourist-with-flask
    command: flask --debug run
    environment:
      FLASK_RUN_HOST: "0.0.0.0"
      # The default port, 5000, conflicts with an MacOS service so listen to 5001 instead. See
      # https://twissmueller.medium.com/resolving-the-problem-of-port-5000-already-being-in-use-dd2fe4bad0be
      FLASK_RUN_PORT: "5001"
    ports:
      - "5001:5001"
    volumes:
      - ../:/workspace/tourist-with-flask

  prefectagentdev:
    image: ghcr.io/tomgobravo/tourist-builder:latest
    working_dir: /workspace/tourist-with-flask
    command: prefect agent start -q development
    network_mode: host
    environment:
      PREFECT_API_URL: "http://127.0.0.1:4200/api"
    volumes:
      - ../:/workspace/tourist-with-flask

  prefectoriondev:
    image: ghcr.io/tomgobravo/tourist-builder:latest
    working_dir: /workspace/tourist-with-flask
    command: prefect orion start
    # Use network_mode: host because so the local orion server which listens to 127.0.0.1 by
    # default is reachable from a browser on the host and by prefectagentdevelopment.
    network_mode: host
